#' Download indicator data from the Nature Index database
#'
#' This function retrieves the currently stored values for one or several
#' indicators from the Nature Index (NI) database using the function 
#' `getIndicatorValues` from the `NICalc` package. 
#' 
#' Executing this function requires accessing the NI database through a token
#' generated by `getToken`, and users are prompted to enter their NI database
#' log-in credentials for that purpose. NI database credentials consist of a
#' registered email address and a password. 
#' 
#' @param indicators A vector of character strings representing the Norwegian
#' names (without special characters) of the relevant indicators. The
#' spelling of `indicators` is consistent with the spelling used in the NI 
#' database (field "Name").
#' @param save Logical, default = `FALSE`. If `TRUE`, the downloaded indicator 
#' data is saved in the workspace in a file named `oldIndicatorData.rds`. 
#' @param save_path Character string indicating the directory into which to save
#' the old indicator data. Defaults to the current working directory. 
#'
#' @return A list of objects (one per entry in `indicators`) containing 1) a data frame of 
#' the values of the values of the indicator and 2) a list of distribution 
#' objects quantifying the uncertainty of each indicator value estimate.
#' @export
#'
#' @examples
#' 
downloadData_NIdb <- function(indicators, save = FALSE, save_path = getwd()){
  
  ## Provide user credentials for NI database and request token
  UserName_NIdb <- rstudioapi::askForPassword("NI database username") # = NINA email address
  Password_NIdb <- rstudioapi::askForPassword("NI database password")
  
  ## Get token
  NIcalc::getToken(username = UserName_NIdb,  
                   password = Password_NIdb,
                   url = "https://www8.nina.no/NaturindeksNiCalc")
  
  ## Specify indicators for which to download data
  myIndicators <- NIcalc::getIndicators() %>%
    dplyr::right_join(data.frame(name = indicators), by = 'name')
  
  ## Check if user has access to indicator
  if(any(is.na(myIndicators$id))){
    stop("You do not have access to the requested indicator(s). 
         To request access, contact NINA.")
  }
  
  ## Retrieve old indicator data from NI database
  oldIndicatorData <- list()
  
  for(i in 1:length(indicators)){
    oldIndicatorData[[i]] <- NIcalc::getIndicatorValues(indicatorID = myIndicators$id[i]) 
  }
  names(oldIndicatorData) <- myIndicators$name
  
  ## Save indicator data (optional)
  if(save){
    saveRDS(oldIndicatorData, file = paste0(save_path, "/oldIndicatorData.rds"))
  }
  
  ## Return indicator data
  return(oldIndicatorData)
}
